# Generated by Django 4.1.7 on 2023-03-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_customer_order_orderitem_checkoutdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='checkoutdetail',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='checkoutdetail',
            name='order',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
