# Generated by Django 4.1.7 on 2023-03-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_remove_order_customer_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetail',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myshop.product'),
        ),
    ]
