# Generated by Django 4.1.7 on 2023-03-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_checkoutdetail_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutdetail',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='checkoutdetail',
            name='state',
        ),
        migrations.RemoveField(
            model_name='checkoutdetail',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='checkoutdetail',
            name='name',
            field=models.CharField(default='test_slug', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkoutdetail',
            name='slug',
            field=models.SlugField(default='as', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
